import Head from "next/head";
import Image from "next/image";
import pink from '../../public/ultra.jpg'
import styles from '../../styles/Home.module.css'

export default function About({hello}) {
  console.log("hello");
    return (
    <div> 
     <Head>
        <title>Sample Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2> about page {hello} </h2>
        <Image src={pink} alt="Ulta Jakas" width={100} height={200}/>
      </main>
    </div>
    )
  }
  