// import App, { AppProps } from "next/app";
// import { store } from "./store";
// import { Provider } from "react-redux";
// import withRedux from 'next-redux-wrapper'
// import Header from './Header/Header';
// import Footer from './Footer/Footer';
// import styles from '../styles/Home.module.css';

// function MyApp ({Component, pageProps}: AppProps) {
//     return(
//       <Provider store={store()}>
//         <Header />
//         <div className={styles.container}>
//         <Component {...pageProps} />  
//         </div>
//         <Footer />
//       </Provider>
//     )
// }

// // export default MyApp
// const makeStore = () => store;

// export default withRedux(store)(MyApp);

import React, {FC} from 'react';
import {Provider} from 'react-redux';
import App, {AppProps} from 'next/app';
import {wrapper} from '../redux/store';

import styles from '../styles/Home.module.css';
import '../styles/globals.css';
import Head from 'next/head';
import Layout from '../components/Layout';
import { SET_CONFIG_DATA } from '../redux/slices/configSlice';
// const MyApp: FC<AppProps> = ({Component, ...rest}) => {
//     const {store, props} = wrapper.useWrappedStore(rest);
//     return (
        // <>
        // <Head>   
        // <title>Sample Next App</title>
        // <meta name="description" content="Generated by create next app" />
        // <link rel="icon" href="/NoorFevicon.png" />         
        // <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        // </Head>
        // <Provider store={store}>
        //     <Layout>
        //         <Component {...props.pageProps} />
        //     </Layout>
        // </Provider>
        // </>
//     );
// };
class MyApp extends App {
    static getInitialProps = wrapper.getInitialAppProps(store => async ({Component, ctx}) => {
    const configUrl = 'https://d2xowqqrpfxxjf.cloudfront.net/noorplay/web-noorplayv2.json';
    const configRes = await fetch(configUrl);
    const configContent = await configRes.json();
    store.dispatch(SET_CONFIG_DATA(configContent.screens));
      return {
        pageProps: {
          // Call page-level getInitialProps
          // DON'T FORGET TO PROVIDE STORE TO PAGE
          ...(Component.getInitialProps ? await Component.getInitialProps({...ctx, store}) : {}),
          // Some custom thing for all pages
          pathname: ctx.pathname,
        },
      };
  
    });
  
    render() {
      const {Component, pageProps} = this.props;
      return (
        <>
        <Head>   
        <title>Sample Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NoorFevicon.png" />         
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </>
      );
    }
  }

// export default MyApp;
export default wrapper.withRedux(MyApp);