import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Switch from "@mui/material/Switch";
import { useEffect, useState } from 'react';
import ComponentOne from './components/ComponentOne';
import ComponentTwo from './components/ComponentTwo';

const label = { inputProps: { "aria-label": "Switch demo" } };

export default function Home() {
  const [mobile, setMobile] = useState(false);
  
  const handleToggle = () => {
    setMobile(!mobile);
  }

  return (
    <div>
      <Head>
        <title>Sample Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <main className={styles.main}>      
        <Switch {...label} onClick={handleToggle}/>
        {
          mobile ? <ComponentOne /> : <ComponentTwo />
        }
      </main>
    </div>
  )
}
